name: nus_launcher
version: 1.0.0+1
publish_to: none
description: A new Flutter project for building Launcher Application For Android.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  device_apps: ^2.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/
  uses-material-design: true

