name: nus_launcher
version: 1.0.0+1
publish_to: none
description: A new Flutter project for building Launcher Application For Android.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  device_apps: ^2.2.0
  dropdown_search: ^5.0.2
  intl: ^0.17.0
  reorderable_grid_view: ^2.2.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo/nus_launcher_logo.png"

flutter: 
  assets:
    - assets/logo/
    - assets/icons/
  uses-material-design: true

